// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-bSc9f3m9rZHHkx5eHMMs8-3p8K2jGD8',
    appId: '1:594308239628:web:b0da94a4c6779dafebf929',
    messagingSenderId: '594308239628',
    projectId: 'serveraccess-e87b0',
    authDomain: 'serveraccess-e87b0.firebaseapp.com',
    storageBucket: 'serveraccess-e87b0.appspot.com',
    measurementId: 'G-J6LBDVPMJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_Yc--dFiTQwddM8aGrgMDCSt_oQRfQw',
    appId: '1:594308239628:android:dc2943a5f87432cbebf929',
    messagingSenderId: '594308239628',
    projectId: 'serveraccess-e87b0',
    storageBucket: 'serveraccess-e87b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-inY0BH7ZxVDq7HkNRAcKrQ2LfHJr-9U',
    appId: '1:594308239628:ios:cd350c499210b54febf929',
    messagingSenderId: '594308239628',
    projectId: 'serveraccess-e87b0',
    storageBucket: 'serveraccess-e87b0.appspot.com',
    iosBundleId: 'com.example.serverAccess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-inY0BH7ZxVDq7HkNRAcKrQ2LfHJr-9U',
    appId: '1:594308239628:ios:d11cc6a9c92fe287ebf929',
    messagingSenderId: '594308239628',
    projectId: 'serveraccess-e87b0',
    storageBucket: 'serveraccess-e87b0.appspot.com',
    iosBundleId: 'com.example.serverAccess.RunnerTests',
  );
}
